cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
env:
  global:
  - secure: utN2iuMZQWt4WjtHRPpkdntbahQZRX4v9E/ZDgVGbkm0cY4OlUdfwlDkElJgzfmTHPsjk886Apy4497Egt3FXWzxTlPuNpjLCbc3WfkhLDUvPL4XoMauB0p2SN5ddRYpxfJBQvgtN4j699GNgLewZfuFH3WaciSD1ePkVR74V0znzkrUcJedmLjOc7mESbv7lTrKlny1fOnxGm/HZJJlUsTu48nRMo2AF8igk0HmjEYjZsFGz2sLZkdGbRjW3Fk4kl8wUESlSTYcJt5JJKnCMrxj7e1+qPliOuTRcWVBsOEQI/K/yPFzY/7lo2hom1GEz0jiRWYELnxqn9BJ0g7iB71LBIkjmKWW4DRm6rA09iZmHE6bb1pnXA29WbJNps5S0Nty2xb7FKThygrSPKdpvYnTxUcYK/Qvb2u3xfz9Q1YM4MizghzzV+hODTr5L+JCMDfPHHYwXcs2WMwBmOMFPmUzpcAjzZ1GBxDF0nxYj4sVt7ahCeNmNzBKiuY5xt9gbGTGc+7+XvW1BBForYS9nT5yQpiqo8kV4FMaVabTkomT8cUC6gI/0V/YSX6GpFQ1hbNhNX1PpITeRRaj9VncvIsqLf0gc87wPKsQWLlRsyM7Je3bBSS6j5NzLBJjjevyrAN2gIEJINNypaQl/F1SFk9Zv+cc12Wht/wOVfb41mA=
  - secure: G8SwCgubaKYBgUATmygb45im8+zFk5pZWs/CUytecY1M3T9ZbW92oN7lTAHg6AOZOE3yIrmSeg4EHC1adSBxVZVls+BUkJzGvVb5bO1s9udTdhHDcik3D07vHZKIGPt8t8ehSJtX1ukynuYoYlanBcz3fjGUfbfI8W2ovKKd4skxU2T/9ZLTOqcmFcdoEO7SrxyQOMETJNXLE2CKEvegNKN1LttOAStPr5FIoF5kXWpSX4H6fk6KOsFEjGCWSe2Mi7aF78bKr+a+mI/Y3VlTwmCsLSSQyBnggMmSKZTOyEVq3/UFBllDP1tc2Q0joPucKQLvz2GxYzhtkZ8JBeiwhbdK5UmV1BiM5bztaSZ9cHWfbVmEdloQ0l1lJFKT4hG6LoM9z53r42XGr4OKVFOo/WhgQXz3LY1+TohCLFDKoYM898wmzMQvBfQkngUpOA63hRCBDibzMB88GesNvAmGzFp4uKIZ7ikj+rovTz8kFGG6JFwldjTglRLenQzU/fCsFQfIEEXpHTZ8NqRg0Fl2voTCdYoBABBEcKAEVl6/eRpouIuyR3Qn48RMuda5/7cENcu3N+CVjkDTfmCbeP1xmSf8G2lCzfZTNzILI0aVmBP6cdgXlol0NIUUDGUMptfUKT5iF1ezrfbs1Nug0hrvGU2MivaaeqNSpmBqmHmncy4=
